[project]
name = "mistral-ocr"
version = "0.1.0"
description = "Mistral OCR"
readme = "README.md"
requires-python = ">=3.10.1, <3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.5.1",
    "jupyter>=1.1.1",
    "mcp[cli]>=1.9.1",
    "mistralai>=1.7.1",
]
